### ISSUE TITLE
SmbFile .renameTo throws exception when a path contains '&' character

### ISSUE THREAD

**Issue by agdula** [kohsuke/jcifs#2]
public class SmbFileTest {
    
        @Test
        public void testAmperstand() throws Exception {
            String targetLocation = "smb://dfworks:dfwadmin@dfworks-dev-ag/d$/tmp/hello&goodbye";
            SmbFile targetLocationFile = new SmbFile(targetLocation);
            if(!targetLocationFile.exists()){
                targetLocationFile.mkdirs();
            }
            SmbFile smbFile = new SmbFile(targetLocation+"/to.tmp");
            IOUtils.write("content",smbFile.getOutputStream());
            SmbFile smbFileDest = new SmbFile(targetLocation+"/to.txt");
            smbFile.renameTo(smbFileDest);
        }
    }

 result is wired exception coming from smbFile.renameTo(smbFileDest);

    jcifs.smb.SmbException: The process cannot access the file because it is being used by another process.

**Comment by Eng3l** [comment]
did you try to close the OutputStream?

**Comment by agdula** [comment]
Yup! It did the trick. Thanks
